name: Create Weekly Readings
on:
  schedule:
    - cron: '0 0 * * 6' # 週に一回、土曜日の0時に実行
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: peter-evans/create-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: 'Weekly Issue' # Issueのタイトル
          body: 'This is the weekly issue.' # Issueの本文
