name: Create Weekly Readings
on:
  schedule:
    - cron: '0 0 * * 6' # 週に一回、土曜日の0時に実行
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        run: |
          curl --location --request POST 'https://api.github.com/repos/moxak/reading-materials/issues' \
          --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "title": "Weekly Issue",
              "body": ""
          }'